env_variables:
  # 環境
  ENV: "staging"

  # GCPサービス接続の資格情報
  GOOGLE_APPLICATION_CREDENTIALS: "./credentials.json"

  # 最小ログレベル
  MIN_LOG_LEVEL: "DEBUG"

  # 内部認証
  INTERNAL_AUTH_TOKEN: "token"

  # ベーシック認証
  BASIC_AUTH_USER: "sample_user"
  BASIC_AUTH_PASSWORD: "sample_password"

  # CloudSQL接続情報
  CLOUDSQL_SAMPLE_CONNECTION_NAME: ""
  CLOUDSQL_SAMPLE_USER: ""
  CLOUDSQL_SAMPLE_PASSWORD: ""
  CLOUDSQL_SAMPLE_DATABASE: ""
